# Comprehensive plant database for Homestead Tracker
# Based on Eliot Coleman and Nico Jabour's winter gardening techniques
# Expanded to include 60+ varieties for full homestead production

PLANT_DATABASE = [
    # ========== WINTER HARDY GREENS ==========
    {
        'id': 'spinach-1',
        'name': 'Spinach',
        'scientificName': 'Spinacia oleracea',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 40,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['lettuce-1', 'radish-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 35, 'max': 75},
        'transplantWeeksBefore': 6,
        'notes': 'Excellent for winter harvest. Grows well under row covers.'
    },
    {
        'id': 'kale-1',
        'name': 'Kale (Lacinato)',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'beet-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'bean-bush-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 40, 'max': 85},
        'transplantWeeksBefore': 6,
        'notes': 'Sweetens after frost. Survives to 10°F with protection.'
    },
    {
        'id': 'lettuce-1',
        'name': 'Lettuce (Mixed)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 45,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'transplantWeeksBefore': 4,
        'notes': 'Succession plant every 2 weeks.'
    },
    {
        'id': 'arugula-1',
        'name': 'Arugula',
        'scientificName': 'Eruca vesicaria',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 30,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['lettuce-1', 'spinach-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 70},
        'transplantWeeksBefore': 4,
        'notes': 'Fast growing, peppery greens. Bolt-resistant in cool weather.'
    },
    {
        'id': 'chard-1',
        'name': 'Swiss Chard',
        'scientificName': 'Beta vulgaris',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 18,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'beet-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 50, 'max': 85},
        'transplantWeeksBefore': 4,
        'notes': 'Colorful and productive. Cut-and-come-again harvest.'
    },

    # ========== ROOT VEGETABLES ==========
    {
        'id': 'carrot-1',
        'name': 'Carrot',
        'scientificName': 'Daucus carota',
        'category': 'vegetable',
        'spacing': 2,
        'rowSpacing': 12,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'lettuce-1', 'rosemary-1'],
        'incompatiblePlants': ['dill-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 0,
        'notes': 'Can overwinter in ground with mulch. Needs deep, loose soil.'
    },
    {
        'id': 'beet-1',
        'name': 'Beet',
        'scientificName': 'Beta vulgaris',
        'category': 'vegetable',
        'spacing': 3,
        'rowSpacing': 12,
        'daysToMaturity': 55,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'kale-1', 'lettuce-1'],
        'incompatiblePlants': ['bean-pole-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 50, 'max': 85},
        'transplantWeeksBefore': 4,
        'notes': 'Greens are also edible and cold-hardy.'
    },
    {
        'id': 'radish-1',
        'name': 'Radish',
        'scientificName': 'Raphanus sativus',
        'category': 'vegetable',
        'spacing': 2,
        'rowSpacing': 6,
        'daysToMaturity': 25,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['lettuce-1', 'spinach-1', 'nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 0,
        'notes': 'Fast growing. Great for spring and fall.'
    },
    {
        'id': 'potato-1',
        'name': 'Potato',
        'scientificName': 'Solanum tuberosum',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 30,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'horseradish-1'],
        'incompatiblePlants': ['tomato-1', 'squash-summer-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.0, 'max': 6.0},
        'plantingDepth': 4,
        'germinationTemp': {'min': 45, 'max': 55},
        'transplantWeeksBefore': 2,
        'notes': 'Hill soil as plants grow. Store in cool, dark place.'
    },

    # ========== BRASSICAS (COLE CROPS) ==========
    {
        'id': 'broccoli-1',
        'name': 'Broccoli',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 65,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'sage-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'strawberry-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 4,
        'notes': 'Harvest side shoots after main head for extended production.'
    },
    {
        'id': 'cauliflower-1',
        'name': 'Cauliflower',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'sage-1'],
        'incompatiblePlants': ['tomato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 4,
        'notes': 'Blanch heads by tying leaves over them.'
    },
    {
        'id': 'cabbage-1',
        'name': 'Cabbage',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 15,
        'rowSpacing': 24,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'bean-pole-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 4,
        'notes': 'Good for sauerkraut. Storage varieties available.'
    },

    # ========== BEANS & PEAS ==========
    {
        'id': 'bean-bush-1',
        'name': 'Bean (Bush)',
        'scientificName': 'Phaseolus vulgaris',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cucumber-1', 'potato-1', 'marigold-1'],
        'incompatiblePlants': ['onion-1', 'garlic-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 85},
        'transplantWeeksBefore': 0,
        'notes': 'Nitrogen fixer. Plant after last frost.'
    },
    {
        'id': 'bean-pole-1',
        'name': 'Bean (Pole)',
        'scientificName': 'Phaseolus vulgaris',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 24,
        'daysToMaturity': 65,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cucumber-1', 'sunflower-1'],
        'incompatiblePlants': ['onion-1', 'beet-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 85},
        'transplantWeeksBefore': 0,
        'notes': 'Needs trellis. More productive than bush beans.'
    },
    {
        'id': 'pea-1',
        'name': 'Pea (Shelling)',
        'scientificName': 'Pisum sativum',
        'category': 'vegetable',
        'spacing': 2,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'radish-1', 'cucumber-1'],
        'incompatiblePlants': ['onion-1', 'garlic-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 40, 'max': 75},
        'transplantWeeksBefore': 6,
        'notes': 'Plant early spring. Nitrogen fixer.'
    },

    # ========== SUMMER CROPS (TOMATOES, PEPPERS, EGGPLANT) ==========
    {
        'id': 'tomato-1',
        'name': 'Tomato (Beefsteak)',
        'scientificName': 'Solanum lycopersicum',
        'category': 'vegetable',
        'spacing': 24,
        'rowSpacing': 36,
        'daysToMaturity': 80,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'carrot-1', 'parsley-1', 'marigold-1'],
        'incompatiblePlants': ['kale-1', 'potato-1', 'fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 85},
        'transplantWeeksBefore': -2,
        'notes': 'Indeterminate. Needs staking. Deep watering.'
    },
    {
        'id': 'tomato-cherry-1',
        'name': 'Tomato (Cherry)',
        'scientificName': 'Solanum lycopersicum',
        'category': 'vegetable',
        'spacing': 24,
        'rowSpacing': 36,
        'daysToMaturity': 60,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'nasturtium-1'],
        'incompatiblePlants': ['kale-1', 'potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 85},
        'transplantWeeksBefore': -2,
        'notes': 'Prolific producer. Great for snacking and salads.'
    },
    {
        'id': 'pepper-bell-1',
        'name': 'Pepper (Bell)',
        'scientificName': 'Capsicum annuum',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'onion-1', 'oregano-1'],
        'incompatiblePlants': ['fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 85},
        'transplantWeeksBefore': -2,
        'notes': 'Harvest green or let ripen to red/yellow.'
    },
    {
        'id': 'pepper-hot-1',
        'name': 'Pepper (Hot/Jalapeño)',
        'scientificName': 'Capsicum annuum',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 70,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'oregano-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 85},
        'transplantWeeksBefore': -2,
        'notes': 'Very productive. Great for pickling and salsa.'
    },

    # ========== SQUASH, CUCUMBERS, MELONS ==========
    {
        'id': 'squash-summer-1',
        'name': 'Squash (Summer/Zucchini)',
        'scientificName': 'Cucurbita pepo',
        'category': 'vegetable',
        'spacing': 24,
        'rowSpacing': 36,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'transplantWeeksBefore': -1,
        'notes': 'Harvest small for best flavor. Very productive.'
    },
    {
        'id': 'squash-winter-1',
        'name': 'Squash (Winter/Butternut)',
        'scientificName': 'Cucurbita moschata',
        'category': 'vegetable',
        'spacing': 36,
        'rowSpacing': 60,
        'daysToMaturity': 95,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'nasturtium-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'transplantWeeksBefore': -1,
        'notes': 'Excellent storage. Cure before storing.'
    },
    {
        'id': 'cucumber-1',
        'name': 'Cucumber',
        'scientificName': 'Cucumis sativus',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 60,
        'daysToMaturity': 55,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'pea-1', 'radish-1', 'dill-1'],
        'incompatiblePlants': ['potato-1', 'sage-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'transplantWeeksBefore': 0,
        'notes': 'Trellis for straight fruit. Pickle small cukes.'
    },
    {
        'id': 'melon-1',
        'name': 'Melon (Cantaloupe)',
        'scientificName': 'Cucumis melo',
        'category': 'vegetable',
        'spacing': 24,
        'rowSpacing': 60,
        'daysToMaturity': 85,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 95},
        'transplantWeeksBefore': -1,
        'notes': 'Needs warm soil and long season. Sweet when ripe.'
    },
    {
        'id': 'watermelon-1',
        'name': 'Watermelon',
        'scientificName': 'Citrullus lanatus',
        'category': 'vegetable',
        'spacing': 36,
        'rowSpacing': 72,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 95},
        'transplantWeeksBefore': -2,
        'notes': 'Needs lots of space and heat. Hollow sound when ripe.'
    },

    # ========== ALLIUMS (ONIONS, GARLIC, LEEKS) ==========
    {
        'id': 'onion-1',
        'name': 'Onion (Storage)',
        'scientificName': 'Allium cepa',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 110,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'beet-1', 'lettuce-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1', 'sage-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 50, 'max': 95},
        'transplantWeeksBefore': 8,
        'notes': 'Can be planted as sets. Cure for storage.'
    },
    {
        'id': 'garlic-1',
        'name': 'Garlic',
        'scientificName': 'Allium sativum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 240,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'rose-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 2,
        'germinationTemp': {'min': 32, 'max': 50},
        'transplantWeeksBefore': 0,
        'notes': 'Plant in fall. Harvest when leaves brown. Cure for storage.'
    },
    {
        'id': 'leek-1',
        'name': 'Leek',
        'scientificName': 'Allium ampeloprasum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 120,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'onion-1'],
        'incompatiblePlants': ['bean-bush-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 45, 'max': 85},
        'transplantWeeksBefore': 8,
        'notes': 'Hill soil for long white shanks. Very cold hardy.'
    },
    {
        'id': 'chives-1',
        'name': 'Chives',
        'scientificName': 'Allium schoenoprasum',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'tomato-1', 'rose-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 6,
        'notes': 'Perennial. Edible flowers. Repels aphids.'
    },

    # ========== CULINARY HERBS ==========
    {
        'id': 'basil-1',
        'name': 'Basil (Sweet)',
        'scientificName': 'Ocimum basilicum',
        'category': 'herb',
        'spacing': 10,
        'rowSpacing': 12,
        'daysToMaturity': 60,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'pepper-bell-1', 'oregano-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 85},
        'transplantWeeksBefore': -1,
        'notes': 'Pinch flowers for bushier plant. Repels flies and mosquitoes.'
    },
    {
        'id': 'parsley-1',
        'name': 'Parsley',
        'scientificName': 'Petroselinum crispum',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'asparagus-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 50, 'max': 80},
        'transplantWeeksBefore': 4,
        'notes': 'Slow to germinate. Biennial. Overwinters well.'
    },
    {
        'id': 'cilantro-1',
        'name': 'Cilantro/Coriander',
        'scientificName': 'Coriandrum sativum',
        'category': 'herb',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 45,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'anise-1'],
        'incompatiblePlants': ['fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.2, 'max': 6.8},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 55, 'max': 68},
        'transplantWeeksBefore': 2,
        'notes': 'Bolts in heat. Succession plant. Seeds are coriander spice.'
    },
    {
        'id': 'dill-1',
        'name': 'Dill',
        'scientificName': 'Anethum graveolens',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['cucumber-1', 'lettuce-1', 'onion-1'],
        'incompatiblePlants': ['carrot-1', 'tomato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 0,
        'notes': 'Attracts beneficial insects. Great for pickles.'
    },
    {
        'id': 'oregano-1',
        'name': 'Oregano',
        'scientificName': 'Origanum vulgare',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 80,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['pepper-bell-1', 'tomato-1', 'basil-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 6,
        'notes': 'Perennial. Drought tolerant. Stronger flavor when dried.'
    },
    {
        'id': 'thyme-1',
        'name': 'Thyme',
        'scientificName': 'Thymus vulgaris',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['cabbage-1', 'tomato-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 8,
        'notes': 'Perennial. Drought tolerant. Repels cabbage worms.'
    },
    {
        'id': 'sage-1',
        'name': 'Sage',
        'scientificName': 'Salvia officinalis',
        'category': 'herb',
        'spacing': 24,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'cabbage-1', 'strawberry-1'],
        'incompatiblePlants': ['cucumber-1', 'onion-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 6,
        'notes': 'Perennial. Repels cabbage moths and carrot flies.'
    },
    {
        'id': 'rosemary-1',
        'name': 'Rosemary',
        'scientificName': 'Rosmarinus officinalis',
        'category': 'herb',
        'spacing': 24,
        'rowSpacing': 24,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cabbage-1', 'sage-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 65, 'max': 70},
        'transplantWeeksBefore': 8,
        'notes': 'Perennial in warm climates. Repels cabbage moths and bean beetles.'
    },
    {
        'id': 'mint-1',
        'name': 'Mint (Spearmint)',
        'scientificName': 'Mentha spicata',
        'category': 'herb',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['cabbage-1', 'tomato-1'],
        'incompatiblePlants': ['parsley-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 70},
        'transplantWeeksBefore': 6,
        'notes': 'Perennial. INVASIVE - grow in containers! Repels ants and aphids.'
    },

    # ========== COMPANION FLOWERS ==========
    {
        'id': 'marigold-1',
        'name': 'Marigold (French)',
        'scientificName': 'Tagetes patula',
        'category': 'flower',
        'spacing': 10,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'bean-bush-1', 'squash-summer-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 75},
        'transplantWeeksBefore': 0,
        'notes': 'Repels nematodes, aphids, and whiteflies. Attracts pollinators.'
    },
    {
        'id': 'nasturtium-1',
        'name': 'Nasturtium',
        'scientificName': 'Tropaeolum majus',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['cucumber-1', 'radish-1', 'squash-summer-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 65, 'max': 70},
        'transplantWeeksBefore': -1,
        'notes': 'Edible flowers and leaves. Trap crop for aphids. Repels squash bugs.'
    },
    {
        'id': 'sunflower-1',
        'name': 'Sunflower',
        'scientificName': 'Helianthus annuus',
        'category': 'flower',
        'spacing': 24,
        'rowSpacing': 30,
        'daysToMaturity': 80,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-pole-1', 'cucumber-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 85},
        'transplantWeeksBefore': -1,
        'notes': 'Attracts birds and pollinators. Can provide shade and trellis.'
    },
    {
        'id': 'zinnia-1',
        'name': 'Zinnia',
        'scientificName': 'Zinnia elegans',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 60,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 80},
        'transplantWeeksBefore': -1,
        'notes': 'Attracts butterflies and beneficial insects. Great cut flower.'
    },
    {
        'id': 'calendula-1',
        'name': 'Calendula (Pot Marigold)',
        'scientificName': 'Calendula officinalis',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'lettuce-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 2,
        'notes': 'Edible and medicinal. Attracts beneficial insects. Repels aphids.'
    },
    {
        'id': 'borage-1',
        'name': 'Borage',
        'scientificName': 'Borago officinalis',
        'category': 'flower',
        'spacing': 18,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'squash-summer-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 0,
        'notes': 'Attracts bees. Edible flowers. Deters tomato hornworms.'
    },

    # ========== BERRIES & FRUITS ==========
    {
        'id': 'strawberry-1',
        'name': 'Strawberry',
        'scientificName': 'Fragaria × ananassa',
        'category': 'fruit',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['spinach-1', 'lettuce-1', 'thyme-1', 'borage-1'],
        'incompatiblePlants': ['cabbage-1', 'broccoli-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'transplantWeeksBefore': 0,
        'notes': 'Perennial. Plant crown at soil level. Mulch heavily for winter.'
    },
    {
        'id': 'raspberry-1',
        'name': 'Raspberry',
        'scientificName': 'Rubus idaeus',
        'category': 'fruit',
        'spacing': 24,
        'rowSpacing': 72,
        'daysToMaturity': 365,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['garlic-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 3,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 0,
        'notes': 'Perennial. Fruits on second-year canes. Needs support.'
    },
    {
        'id': 'blueberry-1',
        'name': 'Blueberry',
        'scientificName': 'Vaccinium corymbosum',
        'category': 'fruit',
        'spacing': 48,
        'rowSpacing': 72,
        'daysToMaturity': 730,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 4.5, 'max': 5.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'transplantWeeksBefore': 0,
        'notes': 'Perennial shrub. Needs acidic soil. Plant 2+ varieties for pollination.'
    }
]

# Compost materials with C:N ratios
COMPOST_MATERIALS = {
    'grass-clippings': {'type': 'green', 'cnRatio': 20},
    'food-scraps': {'type': 'green', 'cnRatio': 15},
    'coffee-grounds': {'type': 'green', 'cnRatio': 20},
    'fresh-manure': {'type': 'green', 'cnRatio': 10},
    'chicken-manure': {'type': 'green', 'cnRatio': 12},
    'hay-fresh': {'type': 'green', 'cnRatio': 15},
    'garden-waste': {'type': 'green', 'cnRatio': 30},
    'dried-leaves': {'type': 'brown', 'cnRatio': 60},
    'straw': {'type': 'brown', 'cnRatio': 80},
    'wood-chips': {'type': 'brown', 'cnRatio': 400},
    'cardboard': {'type': 'brown', 'cnRatio': 350},
    'paper': {'type': 'brown', 'cnRatio': 175},
    'sawdust': {'type': 'brown', 'cnRatio': 500},
    'corn-stalks': {'type': 'brown', 'cnRatio': 60},
    'pine-needles': {'type': 'brown', 'cnRatio': 80}
}

def get_plant_by_id(plant_id):
    """Get plant details by ID"""
    for plant in PLANT_DATABASE:
        if plant['id'] == plant_id:
            return plant
    return None

def get_winter_hardy_plants():
    """Get all winter-hardy plants"""
    return [p for p in PLANT_DATABASE if p['winterHardy']]

def get_plants_by_category(category):
    """Get plants by category"""
    return [p for p in PLANT_DATABASE if p['category'] == category]

def get_companion_plants(plant_id):
    """Get recommended companion plants for a given plant"""
    plant = get_plant_by_id(plant_id)
    if not plant:
        return []

    companions = []
    for comp_id in plant.get('companionPlants', []):
        comp = get_plant_by_id(comp_id)
        if comp:
            companions.append(comp)
    return companions

def get_incompatible_plants(plant_id):
    """Get incompatible plants for a given plant"""
    plant = get_plant_by_id(plant_id)
    if not plant:
        return []

    incompatible = []
    for incomp_id in plant.get('incompatiblePlants', []):
        incomp = get_plant_by_id(incomp_id)
        if incomp:
            incompatible.append(incomp)
    return incompatible
